"""initial schema

Revision ID: b5e10453f989
Revises: 
Create Date: 2026-09-30 22:25:11.000871

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.db.fts import create_fts_schema


revision = 'b5e10453f989'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label_bn', sa.String(length=80), nullable=False),
    sa.Column('label_en', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_subjects_code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=False)

    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name_bn', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('theme', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_slug'), ['slug'], unique=True)

    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('min_app_version', sa.String(length=20), nullable=False),
    sa.Column('latest_app_version', sa.String(length=20), nullable=False),
    sa.Column('force_update', sa.Boolean(), nullable=False),
    sa.Column('sync_message', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', name='uq_app_config_university')
    )
    op.create_table('app_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_app_keys_key_hash'),
    sa.UniqueConstraint('university_id', 'label', name='uq_app_keys_university_label')
    )
    with op.batch_alter_table('app_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_keys_university_id'), ['university_id'], unique=False)

    op.create_table('content_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', name='uq_content_meta_university')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=8), nullable=False),
    sa.Column('title_bn', sa.String(length=80), nullable=False),
    sa.Column('title_en', sa.String(length=80), nullable=True),
    sa.Column('faculty_bn', sa.String(length=120), nullable=False),
    sa.Column('subjects_label', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'letter', name='uq_units_university_letter')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_university_id'), ['university_id'], unique=False)
        batch_op.create_index('ix_units_university_sort', ['university_id', 'sort_order'], unique=False)

    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_admin_audit_created', ['created_at'], unique=False)

    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('label_bn', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('subjects_label', sa.String(length=200), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'year', name='uq_papers_unit_year')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index('ix_papers_unit_year', ['unit_id', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_university_id'), ['university_id'], unique=False)
        batch_op.create_index('ix_papers_university_published', ['university_id', 'is_published'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('target_university_id', sa.Integer(), nullable=True),
    sa.Column('target_unit_id', sa.Integer(), nullable=True),
    sa.Column('score_percent', sa.Integer(), nullable=False),
    sa.Column('weekly_solved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', name='uq_users_device_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_users_last_seen', ['last_seen_at'], unique=False)

    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('answered', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('wrong', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sessions_paper', ['paper_id'], unique=False)
        batch_op.create_index('ix_sessions_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.Integer(), nullable=False),
    sa.Column('chapter_bn', sa.String(length=160), nullable=False),
    sa.Column('stem_bn', sa.Text(), nullable=False),
    sa.Column('stem_en', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation_bn', sa.Text(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('shortcut_bn', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('analytics_percent', sa.Integer(), nullable=False),
    sa.Column('analytics_attempts', sa.Integer(), nullable=False),
    sa.Column('analytics_correct', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'serial', name='uq_questions_paper_serial')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index('ix_questions_paper_subject_serial', ['paper_id', 'subject_id', 'serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_university_id'), ['university_id'], unique=False)
        batch_op.create_index('ix_questions_university_published_updated', ['university_id', 'is_published', 'updated_at'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_bookmarks_user_question')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_question_id'), ['question_id'], unique=False)
        batch_op.create_index('ix_bookmarks_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=4), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'letter', name='uq_options_question_letter')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index('ix_options_question_sort', ['question_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    op.create_table('session_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_answers_session_question')
    )
    with op.batch_alter_table('session_answers', schema=None) as batch_op:
        batch_op.create_index('ix_answers_question', ['question_id'], unique=False)
        batch_op.create_index('ix_answers_session', ['session_id'], unique=False)

    # ### end Alembic commands ###

    create_fts_schema(op.get_bind())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS questions_fts_au")
    op.execute("DROP TRIGGER IF EXISTS questions_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS questions_fts_ai")
    op.execute("DROP TABLE IF EXISTS questions_fts")
    with op.batch_alter_table('session_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_session')
        batch_op.drop_index('ix_answers_question')

    op.drop_table('session_answers')
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))
        batch_op.drop_index('ix_options_question_sort')

    op.drop_table('question_options')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_user_id'))
        batch_op.drop_index('ix_bookmarks_user_created')
        batch_op.drop_index(batch_op.f('ix_bookmarks_question_id'))

    op.drop_table('bookmarks')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_university_published_updated')
        batch_op.drop_index(batch_op.f('ix_questions_university_id'))
        batch_op.drop_index(batch_op.f('ix_questions_unit_id'))
        batch_op.drop_index(batch_op.f('ix_questions_subject_id'))
        batch_op.drop_index('ix_questions_paper_subject_serial')
        batch_op.drop_index(batch_op.f('ix_questions_paper_id'))

    op.drop_table('questions')
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_created')
        batch_op.drop_index('ix_sessions_paper')
        batch_op.drop_index(batch_op.f('ix_practice_sessions_user_id'))

    op.drop_table('practice_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_last_seen')
        batch_op.drop_index(batch_op.f('ix_users_device_id'))

    op.drop_table('users')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index('ix_papers_university_published')
        batch_op.drop_index(batch_op.f('ix_papers_university_id'))
        batch_op.drop_index('ix_papers_unit_year')
        batch_op.drop_index(batch_op.f('ix_papers_unit_id'))

    op.drop_table('papers')
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_audit_created')

    op.drop_table('admin_audit_log')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index('ix_units_university_sort')
        batch_op.drop_index(batch_op.f('ix_units_university_id'))

    op.drop_table('units')
    op.drop_table('content_meta')
    with op.batch_alter_table('app_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_keys_university_id'))
        batch_op.drop_index(batch_op.f('ix_app_keys_key_hash'))

    op.drop_table('app_keys')
    op.drop_table('app_config')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_slug'))

    op.drop_table('universities')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    # ### end Alembic commands ###
